import type { SpeciesDefinition, SpeciesId } from "./types.js";

export const SPECIES: Record<SpeciesId, SpeciesDefinition> = {
  moonbell: {
    id: "moonbell",
    name: "Moonbell",
    emoji: "◡̈",
    description: "A pale bell flower that opens in quiet evening light.",
    preferredSeasons: ["spring", "autumn"],
    daysToSprout: 2,
    daysToBud: 7,
    daysToMature: 13,
    waterPreference: 58,
    resilience: 72,
    colors: ["#d9d7ff", "#eee9ff", "#b9b5e8"]
  },
  starpetal: {
    id: "starpetal",
    name: "Starpetal",
    emoji: "✦",
    description: "A small many-pointed flower that gathers in bright clusters.",
    preferredSeasons: ["spring", "summer"],
    daysToSprout: 2,
    daysToBud: 6,
    daysToMature: 10,
    waterPreference: 48,
    resilience: 65,
    colors: ["#ffd6e7", "#fff0a8", "#f5b8d1"]
  },
  rainmint: {
    id: "rainmint",
    name: "Rainmint",
    emoji: "⌇",
    description: "Cool green leaves that pearl with water after every shower.",
    preferredSeasons: ["spring", "summer", "autumn"],
    daysToSprout: 1,
    daysToBud: 4,
    daysToMature: 8,
    waterPreference: 72,
    resilience: 82,
    colors: ["#a9dac3", "#c8ead9", "#7fb89c"]
  },
  emberbloom: {
    id: "emberbloom",
    name: "Emberbloom",
    emoji: "✺",
    description: "A warm coral flower that keeps its color through dry afternoons.",
    preferredSeasons: ["summer", "autumn"],
    daysToSprout: 3,
    daysToBud: 9,
    daysToMature: 16,
    waterPreference: 36,
    resilience: 88,
    colors: ["#f0a08d", "#f7c0a7", "#dd796d"]
  },
  duskfern: {
    id: "duskfern",
    name: "Duskfern",
    emoji: "⌁",
    description: "A shade-loving fern whose new fronds unfurl at dusk.",
    preferredSeasons: ["spring", "autumn", "winter"],
    daysToSprout: 3,
    daysToBud: 11,
    daysToMature: 19,
    waterPreference: 65,
    resilience: 92,
    colors: ["#739b86", "#9bb8a4", "#527568"]
  },
  cloverlight: {
    id: "cloverlight",
    name: "Cloverlight",
    emoji: "❋",
    description: "A tiny groundcover that sometimes glows after rain.",
    preferredSeasons: ["spring", "summer", "autumn"],
    daysToSprout: 1,
    daysToBud: 3,
    daysToMature: 7,
    waterPreference: 52,
    resilience: 95,
    colors: ["#cfe58c", "#e3f2ad", "#9fc66b"]
  },
  snowlace: {
    id: "snowlace",
    name: "Snowlace",
    emoji: "✼",
    description: "A frost-bright flower whose fine petals hold their shape through cold mornings.",
    preferredSeasons: ["winter", "spring"],
    daysToSprout: 4,
    daysToBud: 13,
    daysToMature: 22,
    waterPreference: 55,
    resilience: 96,
    colors: ["#f3f7ff", "#cbdcf2", "#a9c2df"]
  },
  sunsigh: {
    id: "sunsigh",
    name: "Sunsigh",
    emoji: "☼",
    description: "A warm, papery bloom that turns its face toward long dry afternoons.",
    preferredSeasons: ["summer", "autumn"],
    daysToSprout: 2,
    daysToBud: 6,
    daysToMature: 11,
    waterPreference: 30,
    resilience: 84,
    colors: ["#f8d36f", "#f3aa55", "#ffe7a3"]
  },
  tideglass: {
    id: "tideglass",
    name: "Tideglass",
    emoji: "◇",
    description: "A translucent blue flower that gathers droplets along every petal edge.",
    preferredSeasons: ["spring", "summer"],
    daysToSprout: 3,
    daysToBud: 8,
    daysToMature: 14,
    waterPreference: 80,
    resilience: 76,
    colors: ["#b9e6e8", "#86cbd1", "#d8f4ef"]
  },
  velvethorn: {
    id: "velvethorn",
    name: "Velvethorn",
    emoji: "◆",
    description: "A slow dark bloom with velvet petals and small silver-edged leaves.",
    preferredSeasons: ["autumn", "winter"],
    daysToSprout: 4,
    daysToBud: 14,
    daysToMature: 24,
    waterPreference: 40,
    resilience: 94,
    colors: ["#75485f", "#9b607b", "#54374f"]
  },
  lanternmoss: {
    id: "lanternmoss",
    name: "Lanternmoss",
    emoji: "◈",
    description: "A damp-loving ground bloom whose tiny cups seem lit at dusk.",
    preferredSeasons: ["autumn", "winter"],
    daysToSprout: 2,
    daysToBud: 7,
    daysToMature: 12,
    waterPreference: 75,
    resilience: 90,
    colors: ["#c9dc79", "#e8c46a", "#9eb968"]
  },
  cloudpoppy: {
    id: "cloudpoppy",
    name: "Cloudpoppy",
    emoji: "✿",
    description: "A soft wide-petaled flower that trembles even when the air seems still.",
    preferredSeasons: ["spring", "summer"],
    daysToSprout: 3,
    daysToBud: 9,
    daysToMature: 15,
    waterPreference: 50,
    resilience: 68,
    colors: ["#c9c9f1", "#f3d9e8", "#eef0ff"]
  }
};

export const SPECIES_LIST = Object.values(SPECIES);
